# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\DeleteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteDialog(object):
    def setupUi(self, DeleteDialog):
        DeleteDialog.setObjectName("DeleteDialog")
        DeleteDialog.resize(400, 300)
        self.PrimaryKey = QtWidgets.QTextEdit(DeleteDialog)
        self.PrimaryKey.setGeometry(QtCore.QRect(140, 20, 104, 31))
        self.PrimaryKey.setObjectName("PrimaryKey")
        self.PrimaryKeyValue = QtWidgets.QTextEdit(DeleteDialog)
        self.PrimaryKeyValue.setGeometry(QtCore.QRect(140, 80, 104, 31))
        self.PrimaryKeyValue.setObjectName("PrimaryKeyValue")
        self.label = QtWidgets.QLabel(DeleteDialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(DeleteDialog)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_6.setObjectName("label_6")
        self.Status = QtWidgets.QLabel(DeleteDialog)
        self.Status.setGeometry(QtCore.QRect(80, 190, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Status.setFont(font)
        self.Status.setText("")
        self.Status.setObjectName("Status")
        self.Deleterow = QtWidgets.QPushButton(DeleteDialog)
        self.Deleterow.setGeometry(QtCore.QRect(140, 230, 93, 28))
        self.Deleterow.setObjectName("Deleterow")

        self.retranslateUi(DeleteDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteDialog)

    def retranslateUi(self, DeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteDialog.setWindowTitle(_translate("DeleteDialog", "Dialog"))
        self.label.setText(_translate("DeleteDialog", "PrimaryKey"))
        self.label_6.setText(_translate("DeleteDialog", "PrimaryKeyValue"))
        self.Deleterow.setText(_translate("DeleteDialog", "Delete row"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteDialog = QtWidgets.QDialog()
    ui = Ui_DeleteDialog()
    ui.setupUi(DeleteDialog)
    DeleteDialog.show()
    sys.exit(app.exec_())
