# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\DialogEmergencyStatusInsert.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEmergencyStatusInsert(object):
    def setupUi(self, DialogEmergencyStatusInsert):
        DialogEmergencyStatusInsert.setObjectName("DialogEmergencyStatusInsert")
        DialogEmergencyStatusInsert.resize(400, 516)
        self.EmergencyStatusID = QtWidgets.QTextEdit(DialogEmergencyStatusInsert)
        self.EmergencyStatusID.setGeometry(QtCore.QRect(210, 40, 171, 31))
        self.EmergencyStatusID.setObjectName("EmergencyStatusID")
        self.EmergencyStatusName = QtWidgets.QTextEdit(DialogEmergencyStatusInsert)
        self.EmergencyStatusName.setGeometry(QtCore.QRect(210, 80, 171, 31))
        self.EmergencyStatusName.setObjectName("EmergencyStatusName")
        self.EmergencyStatusDescription = QtWidgets.QTextEdit(DialogEmergencyStatusInsert)
        self.EmergencyStatusDescription.setGeometry(QtCore.QRect(210, 120, 171, 31))
        self.EmergencyStatusDescription.setObjectName("EmergencyStatusDescription")
        self.label = QtWidgets.QLabel(DialogEmergencyStatusInsert)
        self.label.setGeometry(QtCore.QRect(30, 40, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogEmergencyStatusInsert)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogEmergencyStatusInsert)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 141, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(DialogEmergencyStatusInsert)
        self.pushButton.setGeometry(QtCore.QRect(130, 460, 161, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(DialogEmergencyStatusInsert)
        QtCore.QMetaObject.connectSlotsByName(DialogEmergencyStatusInsert)

    def retranslateUi(self, DialogEmergencyStatusInsert):
        _translate = QtCore.QCoreApplication.translate
        DialogEmergencyStatusInsert.setWindowTitle(_translate("DialogEmergencyStatusInsert", "Dialog"))
        self.label.setText(_translate("DialogEmergencyStatusInsert", "EmergencyStatusID"))
        self.label_2.setText(_translate("DialogEmergencyStatusInsert", "EmergencyStatusName"))
        self.label_3.setText(_translate("DialogEmergencyStatusInsert", "EmergencyStatusDescription"))
        self.pushButton.setText(_translate("DialogEmergencyStatusInsert", "Insert into `emergencyStatus`"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogEmergencyStatusInsert = QtWidgets.QDialog()
    ui = Ui_DialogEmergencyStatusInsert()
    ui.setupUi(DialogEmergencyStatusInsert)
    DialogEmergencyStatusInsert.show()
    sys.exit(app.exec_())
