# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\DialogDepartment.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDepartmentInsert(object):
    def setupUi(self, DialogDepartmentInsert):
        DialogDepartmentInsert.setObjectName("DialogDeparmentInsert")
        DialogDepartmentInsert.resize(400, 618)
        self.pushButton = QtWidgets.QPushButton(DialogDepartmentInsert)
        self.pushButton.setGeometry(QtCore.QRect(160, 560, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(DialogDepartmentInsert)
        self.label.setGeometry(QtCore.QRect(60, 50, 111, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(DialogDepartmentInsert)
        self.textEdit.setGeometry(QtCore.QRect(220, 40, 104, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(DialogDepartmentInsert)
        self.textEdit_2.setGeometry(QtCore.QRect(220, 90, 104, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(DialogDepartmentInsert)
        self.textEdit_3.setGeometry(QtCore.QRect(220, 150, 104, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_2 = QtWidgets.QLabel(DialogDepartmentInsert)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogDepartmentInsert)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 91, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(DialogDepartmentInsert)
        QtCore.QMetaObject.connectSlotsByName(DialogDepartmentInsert)

    def retranslateUi(self, DialogDepartmentInsert):
        _translate = QtCore.QCoreApplication.translate
        DialogDepartmentInsert.setWindowTitle(_translate("DialogDepartmentInsert", "Dialog"))
        self.pushButton.setText(_translate("DialogDepartmentInsert", "Insert"))
        self.label.setText(_translate("DialogDepartmentInsert", "DepartmentID"))
        self.textEdit_3.setHtml(_translate("DialogDepartmentInsert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("DialogDepartmentInsert", "DepartmentDescription"))
        self.label_3.setText(_translate("DialogDepartmentInsert", "DepartmentName"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogDepartmentInsert = QtWidgets.QDialog()
    ui = Ui_DialogDepartmentInsert()
    ui.setupUi(DialogDepartmentInsert)
    DialogDepartmentInsert.show()
    sys.exit(app.exec_())
