# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\DialogAircraftInsert.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAircraftInsert(object):
    def setupUi(self, DialogAircraftInsert):
        DialogAircraftInsert.setObjectName("DialogAircraftInsert")
        DialogAircraftInsert.resize(400, 516)
        self.textEditFlightID = QtWidgets.QTextEdit(DialogAircraftInsert)
        self.textEditFlightID.setGeometry(QtCore.QRect(170, 40, 171, 31))
        self.textEditFlightID.setObjectName("textEditFlightID")
        self.textEditFlightID_2 = QtWidgets.QTextEdit(DialogAircraftInsert)
        self.textEditFlightID_2.setGeometry(QtCore.QRect(170, 80, 171, 31))
        self.textEditFlightID_2.setObjectName("textEditFlightID_2")
        self.textEditFlightID_3 = QtWidgets.QTextEdit(DialogAircraftInsert)
        self.textEditFlightID_3.setGeometry(QtCore.QRect(170, 120, 171, 31))
        self.textEditFlightID_3.setObjectName("textEditFlightID_3")
        self.textEditFlightID_4 = QtWidgets.QTextEdit(DialogAircraftInsert)
        self.textEditFlightID_4.setGeometry(QtCore.QRect(170, 160, 171, 31))
        self.textEditFlightID_4.setObjectName("textEditFlightID_4")
        self.label = QtWidgets.QLabel(DialogAircraftInsert)
        self.label.setGeometry(QtCore.QRect(40, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogAircraftInsert)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogAircraftInsert)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogAircraftInsert)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 101, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(DialogAircraftInsert)
        self.pushButton.setGeometry(QtCore.QRect(130, 460, 141, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(DialogAircraftInsert)
        QtCore.QMetaObject.connectSlotsByName(DialogAircraftInsert)

    def retranslateUi(self, DialogAircraftInsert):
        _translate = QtCore.QCoreApplication.translate
        DialogAircraftInsert.setWindowTitle(_translate("DialogAircraftInsert", "Dialog"))
        self.label.setText(_translate("DialogAircraftInsert", "FlightID"))
        self.label_2.setText(_translate("DialogAircraftInsert", "ArrivalCity"))
        self.label_3.setText(_translate("DialogAircraftInsert", "DepartureCity"))
        self.label_4.setText(_translate("DialogAircraftInsert", "AircraftModelName"))
        self.pushButton.setText(_translate("DialogAircraftInsert", "Insert into `aircraft`"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAircraftInsert = QtWidgets.QDialog()
    ui = Ui_DialogAircraftInsert()
    ui.setupUi(DialogAircraftInsert)
    DialogAircraftInsert.show()
    sys.exit(app.exec_())
