# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\EmployeeInsert.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEmployeeInsert(object):
    def setupUi(self, DialogEmployeeInsert):
        DialogEmployeeInsert.setObjectName("DialogEmployeeInsert")
        DialogEmployeeInsert.resize(400, 501)
        self.FIO = QtWidgets.QTextEdit(DialogEmployeeInsert)
        self.FIO.setGeometry(QtCore.QRect(210, 70, 171, 31))
        self.FIO.setObjectName("FIO")
        self.JobTitle = QtWidgets.QTextEdit(DialogEmployeeInsert)
        self.JobTitle.setGeometry(QtCore.QRect(210, 110, 171, 31))
        self.JobTitle.setObjectName("JobTitle")
        self.PersonnelID = QtWidgets.QTextEdit(DialogEmployeeInsert)
        self.PersonnelID.setGeometry(QtCore.QRect(210, 30, 171, 31))
        self.PersonnelID.setObjectName("PersonnelID")
        self.DepartmentID = QtWidgets.QTextEdit(DialogEmployeeInsert)
        self.DepartmentID.setGeometry(QtCore.QRect(210, 150, 171, 31))
        self.DepartmentID.setObjectName("DepartmentID")
        self.label = QtWidgets.QLabel(DialogEmployeeInsert)
        self.label.setGeometry(QtCore.QRect(30, 40, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogEmployeeInsert)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DialogEmployeeInsert)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogEmployeeInsert)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 121, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(DialogEmployeeInsert)
        self.pushButton.setGeometry(QtCore.QRect(130, 440, 181, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(DialogEmployeeInsert)
        QtCore.QMetaObject.connectSlotsByName(DialogEmployeeInsert)

    def retranslateUi(self, DialogEmployeeInsert):
        _translate = QtCore.QCoreApplication.translate
        DialogEmployeeInsert.setWindowTitle(_translate("DialogEmployeeInsert", "Dialog"))
        self.label.setText(_translate("DialogEmployeeInsert", "PersonnelID"))
        self.label_2.setText(_translate("DialogEmployeeInsert", "FIO"))
        self.label_3.setText(_translate("DialogEmployeeInsert", "JobTitle"))
        self.label_4.setText(_translate("DialogEmployeeInsert", "DepartmentID"))
        self.pushButton.setText(_translate("DialogEmployeeInsert", "Insert into `employee`"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogEmployeeInsert = QtWidgets.QDialog()
    ui = Ui_DialogEmployeeInsert()
    ui.setupUi(DialogEmployeeInsert)
    DialogEmployeeInsert.show()
    sys.exit(app.exec_())
