# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\FindInStatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindStatusDialog(object):
    def setupUi(self, FindStatusDialog):
        FindStatusDialog.setObjectName("FindStatusDialog")
        FindStatusDialog.resize(400, 523)
        self.comboBoxColumn = QtWidgets.QComboBox(FindStatusDialog)
        self.comboBoxColumn.setGeometry(QtCore.QRect(260, 70, 111, 22))
        self.comboBoxColumn.setObjectName("comboBoxColumn")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.textEditValue = QtWidgets.QTextEdit(FindStatusDialog)
        self.textEditValue.setGeometry(QtCore.QRect(240, 120, 131, 31))
        self.textEditValue.setObjectName("textEditValue")
        self.label = QtWidgets.QLabel(FindStatusDialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FindStatusDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(FindStatusDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 371, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(FindStatusDialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 470, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(FindStatusDialog)
        QtCore.QMetaObject.connectSlotsByName(FindStatusDialog)

    def retranslateUi(self, FindStatusDialog):
        _translate = QtCore.QCoreApplication.translate
        FindStatusDialog.setWindowTitle(_translate("FindStatusDialog", "Dialog"))
        self.comboBoxColumn.setItemText(0, _translate("FindStatusDialog", "StatusID"))
        self.comboBoxColumn.setItemText(1, _translate("FindStatusDialog", "StatusName"))
        self.comboBoxColumn.setItemText(2, _translate("FindStatusDialog", "Description"))
        self.label.setText(_translate("FindStatusDialog", "Find by column"))
        self.label_2.setText(_translate("FindStatusDialog", "Value to find"))
        self.pushButton.setText(_translate("FindStatusDialog", "Find"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindStatusDialog = QtWidgets.QDialog()
    FindStatusUi = Ui_FindStatusDialog()
    FindStatusUi.setupUi(FindStatusDialog)
    FindStatusDialog.show()
    sys.exit(app.exec_())
