# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\FindInEmergency.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindEmergencyDialog(object):
    def setupUi(self, FindEmergencyDialog):
        FindEmergencyDialog.setObjectName("FindEmergencyDialog")
        FindEmergencyDialog.resize(400, 465)
        self.comboBoxColumn = QtWidgets.QComboBox(FindEmergencyDialog)
        self.comboBoxColumn.setGeometry(QtCore.QRect(240, 70, 111, 22))
        self.comboBoxColumn.setObjectName("comboBoxColumn")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.label = QtWidgets.QLabel(FindEmergencyDialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label.setObjectName("label")
        self.textEditValue = QtWidgets.QTextEdit(FindEmergencyDialog)
        self.textEditValue.setGeometry(QtCore.QRect(220, 120, 131, 31))
        self.textEditValue.setObjectName("textEditValue")
        self.label_2 = QtWidgets.QLabel(FindEmergencyDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(FindEmergencyDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 371, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(FindEmergencyDialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(FindEmergencyDialog)
        QtCore.QMetaObject.connectSlotsByName(FindEmergencyDialog)

    def retranslateUi(self, FindEmergencyDialog):
        _translate = QtCore.QCoreApplication.translate
        FindEmergencyDialog.setWindowTitle(_translate("FindEmergencyDialog", "Dialog"))
        self.comboBoxColumn.setItemText(0, _translate("FindEmergencyDialog", "mergencyStatusID"))
        self.comboBoxColumn.setItemText(1, _translate("FindEmergencyDialog", "EmergencyStatusName"))
        self.comboBoxColumn.setItemText(2, _translate("FindEmergencyDialog", "EmergencyStatusDescription"))
        self.label.setText(_translate("FindEmergencyDialog", "Find by column"))
        self.label_2.setText(_translate("FindEmergencyDialog", "Value to find"))
        self.pushButton.setText(_translate("FindEmergencyDialog", "Find"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindEmergencyDialog = QtWidgets.QDialog()
    FindEmergencyUi = Ui_FindEmergencyDialog()
    FindEmergencyUi.setupUi(FindEmergencyDialog)
    FindEmergencyDialog.show()
    sys.exit(app.exec_())
