# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\FindInDepartment.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindDepartmentDialog(object):
    def setupUi(self, FindDepartmentDialog):
        FindDepartmentDialog.setObjectName("FindDepartmentDialog")
        FindDepartmentDialog.resize(400, 455)
        self.comboBoxColumn = QtWidgets.QComboBox(FindDepartmentDialog)
        self.comboBoxColumn.setGeometry(QtCore.QRect(240, 80, 101, 22))
        self.comboBoxColumn.setObjectName("comboBoxColumn")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.label = QtWidgets.QLabel(FindDepartmentDialog)
        self.label.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.label.setObjectName("label")
        self.textEditValue = QtWidgets.QTextEdit(FindDepartmentDialog)
        self.textEditValue.setGeometry(QtCore.QRect(210, 140, 131, 31))
        self.textEditValue.setObjectName("textEditValue")
        self.label_2 = QtWidgets.QLabel(FindDepartmentDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(FindDepartmentDialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(FindDepartmentDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 190, 381, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(FindDepartmentDialog)
        QtCore.QMetaObject.connectSlotsByName(FindDepartmentDialog)

    def retranslateUi(self, FindDepartmentDialog):
        _translate = QtCore.QCoreApplication.translate
        FindDepartmentDialog.setWindowTitle(_translate("FindDepartmentDialog", "Dialog"))
        self.comboBoxColumn.setItemText(0, _translate("FindDepartmentDialog", "DepartmentID"))
        self.comboBoxColumn.setItemText(1, _translate("FindDepartmentDialog", "DepartmentName"))
        self.comboBoxColumn.setItemText(2, _translate("FindDepartmentDialog", "DepartmentDescription"))
        self.label.setText(_translate("FindDepartmentDialog", "Find by column"))
        self.label_2.setText(_translate("FindDepartmentDialog", "Value to find"))
        self.pushButton.setText(_translate("FindDepartmentDialog", "Find"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindDepartmentDialog = QtWidgets.QDialog()
    FindDepartmentUi = Ui_FindDepartmentDialog()
    FindDepartmentUi.setupUi(FindDepartmentDialog)
    FindDepartmentDialog.show()
    sys.exit(app.exec_())
