# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\FindInEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindEmployeeDialog(object):
    def setupUi(self, FindEmployeeDialog):
        FindEmployeeDialog.setObjectName("FindEmployeeDialog")
        FindEmployeeDialog.resize(400, 468)
        self.comboBoxColumn = QtWidgets.QComboBox(FindEmployeeDialog)
        self.comboBoxColumn.setGeometry(QtCore.QRect(250, 80, 111, 22))
        self.comboBoxColumn.setObjectName("comboBoxColumn")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.textEditValue = QtWidgets.QTextEdit(FindEmployeeDialog)
        self.textEditValue.setGeometry(QtCore.QRect(230, 120, 131, 31))
        self.textEditValue.setObjectName("textEditValue")
        self.tableWidget = QtWidgets.QTableWidget(FindEmployeeDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 371, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(FindEmployeeDialog)
        self.label.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FindEmployeeDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(FindEmployeeDialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(FindEmployeeDialog)
        QtCore.QMetaObject.connectSlotsByName(FindEmployeeDialog)

    def retranslateUi(self, FindEmployeeDialog):
        _translate = QtCore.QCoreApplication.translate
        FindEmployeeDialog.setWindowTitle(_translate("FindEmployeeDialog", "Dialog"))
        self.comboBoxColumn.setItemText(0, _translate("FindEmployeeDialog", "PersonnelID"))
        self.comboBoxColumn.setItemText(1, _translate("FindEmployeeDialog", "FIO"))
        self.comboBoxColumn.setItemText(2, _translate("FindEmployeeDialog", "JobTitle"))
        self.comboBoxColumn.setItemText(3, _translate("FindEmployeeDialog", "DepartmentID"))
        self.label.setText(_translate("FindEmployeeDialog", "Find by column"))
        self.label_2.setText(_translate("FindEmployeeDialog", "Value to find"))
        self.pushButton.setText(_translate("FindEmployeeDialog", "Find"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindEmployeeDialog = QtWidgets.QDialog()
    FindEmployeeDialogUi = Ui_FindEmployeeDialog()
    FindEmployeeDialogUi.setupUi(FindEmployeeDialog)
    FindEmployeeDialog.show()
    sys.exit(app.exec_())
