# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\FindInAircraft.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindAircraftDialog(object):
    def setupUi(self, FindAircraftDialog):
        FindAircraftDialog.setObjectName("FindAircraftDialog")
        FindAircraftDialog.resize(400, 506)
        self.comboBoxColumn = QtWidgets.QComboBox(FindAircraftDialog)
        self.comboBoxColumn.setGeometry(QtCore.QRect(220, 70, 101, 22))
        self.comboBoxColumn.setObjectName("comboBoxColumn")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.comboBoxColumn.addItem("")
        self.label = QtWidgets.QLabel(FindAircraftDialog)
        self.label.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.label.setObjectName("label")
        self.textEditValue = QtWidgets.QTextEdit(FindAircraftDialog)
        self.textEditValue.setGeometry(QtCore.QRect(220, 110, 151, 31))
        self.textEditValue.setObjectName("textEditValue")
        self.label_2 = QtWidgets.QLabel(FindAircraftDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(FindAircraftDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(FindAircraftDialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 440, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(FindAircraftDialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 190, 371, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(FindAircraftDialog)
        QtCore.QMetaObject.connectSlotsByName(FindAircraftDialog)

    def retranslateUi(self, FindAircraftDialog):
        _translate = QtCore.QCoreApplication.translate
        FindAircraftDialog.setWindowTitle(_translate("FindAircraftDialog", "Dialog"))
        self.comboBoxColumn.setItemText(0, _translate("FindAircraftDialog", "FlightID"))
        self.comboBoxColumn.setItemText(1, _translate("FindAircraftDialog", "ArrivalCity"))
        self.comboBoxColumn.setItemText(2, _translate("FindAircraftDialog", "departureCity"))
        self.comboBoxColumn.setItemText(3, _translate("FindAircraftDialog", "AircraftModelname"))
        self.label.setText(_translate("FindAircraftDialog", "Find by column"))
        self.label_2.setText(_translate("FindAircraftDialog", "Value to find"))
        self.pushButton.setText(_translate("FindAircraftDialog", "Find"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindAircraftDialog = QtWidgets.QDialog()
    ui = Ui_FindAircraftDialog()
    ui.setupUi(FindAircraftDialog)
    FindAircraftDialog.show()
    sys.exit(app.exec_())
