# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\TakeoffInsertDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TakeoffDialog(object):
    def setupUi(self, TakeoffDialog):
        TakeoffDialog.setObjectName("TakeoffDialog")
        TakeoffDialog.resize(400, 413)
        self.RequestID = QtWidgets.QTextEdit(TakeoffDialog)
        self.RequestID.setGeometry(QtCore.QRect(190, 30, 161, 31))
        self.RequestID.setObjectName("RequestID")
        self.FlightID = QtWidgets.QTextEdit(TakeoffDialog)
        self.FlightID.setGeometry(QtCore.QRect(190, 80, 161, 31))
        self.FlightID.setObjectName("FlightID")
        self.PersonnelID = QtWidgets.QTextEdit(TakeoffDialog)
        self.PersonnelID.setGeometry(QtCore.QRect(190, 130, 161, 31))
        self.PersonnelID.setObjectName("PersonnelID")
        self.WaitingTime = QtWidgets.QTextEdit(TakeoffDialog)
        self.WaitingTime.setGeometry(QtCore.QRect(190, 180, 161, 31))
        self.WaitingTime.setObjectName("WaitingTime")
        self.StatusID = QtWidgets.QTextEdit(TakeoffDialog)
        self.StatusID.setGeometry(QtCore.QRect(190, 230, 161, 31))
        self.StatusID.setObjectName("StatusID")
        self.label = QtWidgets.QLabel(TakeoffDialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TakeoffDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(TakeoffDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(TakeoffDialog)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(TakeoffDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 47, 13))
        self.label_5.setObjectName("label_5")
        self.takeoffButton = QtWidgets.QPushButton(TakeoffDialog)
        self.takeoffButton.setGeometry(QtCore.QRect(100, 350, 201, 28))
        self.takeoffButton.setObjectName("takeoffButton")

        self.retranslateUi(TakeoffDialog)
        QtCore.QMetaObject.connectSlotsByName(TakeoffDialog)

    def retranslateUi(self, TakeoffDialog):
        _translate = QtCore.QCoreApplication.translate
        TakeoffDialog.setWindowTitle(_translate("TakeoffDialog", "Dialog"))
        self.label.setText(_translate("TakeoffDialog", "RequestID"))
        self.label_2.setText(_translate("TakeoffDialog", "FlightID"))
        self.label_3.setText(_translate("TakeoffDialog", "PersonnelID"))
        self.label_4.setText(_translate("TakeoffDialog", "WaitingTime"))
        self.label_5.setText(_translate("TakeoffDialog", "StatusID"))
        self.takeoffButton.setText(_translate("TakeoffDialog", "Insert into `takeoff_landing_request`"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TakeoffDialog = QtWidgets.QDialog()
    ui_landing = Ui_TakeoffDialog()
    ui_landing.setupUi(TakeoffDialog)
    TakeoffDialog.show()
    sys.exit(app.exec_())
