# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rando\PycharmProjects\MySQLInterface\UpdateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 470)
        self.Column = QtWidgets.QTextEdit(Dialog)
        self.Column.setGeometry(QtCore.QRect(190, 90, 181, 31))
        self.Column.setObjectName("Column")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 47, 13))
        self.label.setObjectName("label")
        self.Table = QtWidgets.QTextEdit(Dialog)
        self.Table.setGeometry(QtCore.QRect(190, 30, 181, 31))
        self.Table.setObjectName("Table")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.PrimaryKey = QtWidgets.QTextEdit(Dialog)
        self.PrimaryKey.setGeometry(QtCore.QRect(190, 150, 181, 31))
        self.PrimaryKey.setObjectName("PrimaryKey")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 71, 16))
        self.label_3.setObjectName("label_3")
        self.newValue = QtWidgets.QTextEdit(Dialog)
        self.newValue.setGeometry(QtCore.QRect(190, 210, 181, 31))
        self.newValue.setObjectName("newValue")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 220, 71, 16))
        self.label_4.setObjectName("label_4")
        self.UpdateButton = QtWidgets.QPushButton(Dialog)
        self.UpdateButton.setGeometry(QtCore.QRect(160, 420, 93, 28))
        self.UpdateButton.setObjectName("UpdateButton")
        self.PrimaryKeyValue = QtWidgets.QTextEdit(Dialog)
        self.PrimaryKeyValue.setGeometry(QtCore.QRect(190, 260, 181, 31))
        self.PrimaryKeyValue.setObjectName("PrimaryKeyValue")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 270, 91, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Column"))
        self.label_2.setText(_translate("Dialog", "Table"))
        self.label_3.setText(_translate("Dialog", "Primary key"))
        self.label_4.setText(_translate("Dialog", "New value"))
        self.UpdateButton.setText(_translate("Dialog", "Update Value"))
        self.label_5.setText(_translate("Dialog", "PriimaryKeyValue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
